apiVersion: v1
kind: ConfigMap
metadata:
  name: first-chart-configmap-{{ .Chart.Version }}
data:
  port: "8080"
  ENV: {{ .Values.env }}
  {{ if eq .Values.env "dev" }}
  testing: true
  {{ else }}
  testing: false
  {{ end }}